#!/usr/bin/env python3
"""Generates project.godot (input map etc.) so the config stays reproducible."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

def key(physical, label=""):
    return ('Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,'
            '"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,'
            f'"keycode":0,"physical_keycode":{physical},"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)')

def mouse(button):
    return ('Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,'
            '"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"button_mask":0,'
            '"position":Vector2(0, 0),"global_position":Vector2(0, 0),"factor":1.0,'
            f'"button_index":{button},"canceled":false,"pressed":false,"double_click":false,"script":null)')

K = dict(W=87, A=65, S=83, D=68, E=69, F=70, Q=81, I=73, C=67, M=77, X=88, H=72, R=82, T=84, J=74, K=75, L=76, O=79, P=80,
         SPACE=32, TAB=4194306, SHIFT=4194325, ESC=4194305, ENTER=4194309, CTRL=4194326, F5=4194336, F9=4194340, F1=4194332,
         UP=4194320, DOWN=4194322, LEFT=4194319, RIGHT=4194321, N1=49, N2=50, N3=51, N4=52, N5=53, N6=54, KP_ENTER=4194310, BACKSPACE=4194308)

actions = {
    "move_forward": [key(K["W"]), key(K["UP"])],
    "move_back": [key(K["S"]), key(K["DOWN"])],
    "move_left": [key(K["A"]), key(K["LEFT"])],
    "move_right": [key(K["D"]), key(K["RIGHT"])],
    "attack": [mouse(1), key(K["J"])],
    "block": [mouse(2), key(K["K"])],
    "roll": [key(K["SPACE"])],
    "sprint": [key(K["SHIFT"])],
    "ranged_toggle": [key(K["F"])],
    "interact": [key(K["E"]), key(K["ENTER"]), key(K["KP_ENTER"])],
    "lock_target": [key(K["TAB"]), mouse(3)],
    "meditate": [key(K["H"])],
    "siddhi_1": [key(K["N1"])], "siddhi_2": [key(K["N2"])], "siddhi_3": [key(K["N3"])],
    "siddhi_4": [key(K["N4"])], "siddhi_5": [key(K["N5"])], "siddhi_6": [key(K["N6"])],
    "potion_prana": [key(K["R"])],
    "potion_ojas": [key(K["T"])],
    "menu_inventory": [key(K["I"])],
    "menu_quests": [key(K["Q"])],
    "menu_codex": [key(K["C"])],
    "menu_map": [key(K["M"])],
    "menu_mudras": [key(K["X"])],
    "menu_sadhana": [key(K["P"])],
    "menu_siddhis": [key(K["O"])],
    "pause": [key(K["ESC"])],
    "quicksave": [key(K["F5"])],
    "quickload": [key(K["F9"])],
    "help": [key(K["F1"])],
    "ui_back": [key(K["BACKSPACE"])],
}

lines = [
    "; Engine configuration file.",
    "; Generated by tools/gen_project.py - edit that script, not this file.",
    "config_version=5", "",
    "[application]", "",
    'config/name="Fable SD - Vira van Jambudvipa"',
    'config/description="A Sanatana Dharma inspired action RPG in the spirit of Fable. Procedural 3D world, yogis, tantrics, siddhis."',
    'run/main_scene="res://scenes/Main.tscn"',
    'config/features=PackedStringArray("4.7", "Forward Plus")',
    'config/icon="res://icon.svg"', "",
    "[autoload]", "",
    'Events="*res://scripts/autoload/Events.gd"',
    'Loc="*res://scripts/autoload/Loc.gd"',
    'Data="*res://scripts/autoload/Data.gd"',
    'Game="*res://scripts/autoload/Game.gd"',
    'Audio="*res://scripts/autoload/Audio.gd"', "",
    "[debug]", "",
    "gdscript/warnings/untyped_declaration=0",
    "gdscript/warnings/unused_parameter=0", "",
    "[display]", "",
    "window/size/viewport_width=1600",
    "window/size/viewport_height=900",
    'window/stretch/mode="canvas_items"',
    'window/stretch/aspect="expand"',
    "window/vsync/vsync_mode=1", "",
    "[input]", "",
]
for name, evs in actions.items():
    lines.append(f'{name}={{\n"deadzone": 0.2,\n"events": [{", ".join(evs)}]\n}}')
lines += ["",
    "[internationalization]", "",
    'locale/fallback="en"', "",
    "[layer_names]", "",
    '3d_physics/layer_1="world"', '3d_physics/layer_2="player"', '3d_physics/layer_3="enemy"',
    '3d_physics/layer_4="npc"', '3d_physics/layer_5="projectile"', '3d_physics/layer_6="interact"',
    '3d_physics/layer_7="hitbox"', "",
    "[physics]", "",
    "3d/default_gravity=12.0",
    "common/physics_ticks_per_second=60", "",
    "[rendering]", "",
    'renderer/rendering_method="forward_plus"',
    'renderer/rendering_method.mobile="mobile"',
    "anti_aliasing/quality/msaa_3d=2",
    "anti_aliasing/quality/screen_space_aa=1",
    "lights_and_shadows/directional_shadow/size=4096",
    "lights_and_shadows/directional_shadow/soft_shadow_filter_quality=3",
    "environment/defaults/default_clear_color=Color(0.05, 0.05, 0.08, 1)",
    "textures/default_filters/anisotropic_filtering_level=2",
    "",
]
with open(os.path.join(ROOT, "project.godot"), "w") as f:
    f.write("\n".join(lines))
print("project.godot written")
